separate scripts for shared K&L line imagers

diff --git a/scripts/camViewer b/scripts/camViewer
--- a/scripts/camViewer
+++ b/scripts/camViewer
@@ -147,7 +147,6 @@ OPTIONS:
 -m|--main           : bring up the edm screen
 -r|--reboot         : reboot the IOC
 -l|--list           : print list of cameras
--u|--rate <#>       : update rate limit in Hz (default 5)
 -H|--hutch <hutch>  : use a specific hutches camviewer config file
 -e|--enable         : enable camera ioc
 -d|--disable        : disable camera ioc
@@ -166,7 +165,6 @@ fi
 LIST=0
 CAMNUM=0
 CAM=0
-RATE=5
 REBOOT=0
 ENABLE=0
 DISABLE=0
@@ -176,7 +174,7 @@ STOP=0
 NUDGE=0
 hutch="" # Initialize hutch
 
-if ! OPTIONS=$(getopt -o lmredasnc:w:u:H: --long list,main,reboot,enable,disable,acquire,stop,nudge,cam:,wait:,rate:,hutch: -n \'"$0"\' -- "$@"); then
+if ! OPTIONS=$(getopt -o lmredasnc:w:u:H: --long list,main,reboot,enable,disable,acquire,stop,nudge,cam:,wait:,hutch: -n \'"$0"\' -- "$@"); then
     echo "Terminating..." >&2
     exit 1
 fi
@@ -192,10 +190,6 @@ do
             ;;
         -c|--cam)
             CAM=$2
-            shift 2
-            ;;
-        -u|--rate)
-            RATE=$2
             shift 2
             ;;
         -H|--hutch)
@@ -376,39 +370,38 @@ if [ $NUDGE -gt 0 ]; then
     exit
 fi
 
-IS_ACQUIRING=$(caget -t -n "$CAMPVFULL":Acquire_RBV)
-if isNum "$IS_ACQUIRING"; then
-    if [ "$IS_ACQUIRING" -eq 0 ]; then
-        echo 'start acquiring for camera ' "$CAMNAME"
-        caput -n "$CAMPVFULL":Acquire 1
-    fi
-else
-    echo 'cannot check Acquiring PV, try to open camera viewer anyways....'
-fi
-
-if [[ -z "$IS_REMOTE_SSH" ]]; then
-    current_host="$(hostname)"
-    if [[ "$hutch" == "kfe" && "$current_host" != "kfe-console" && "$current_host" != "xbdo-control" ]]; then
-        echo "Not in SSH, connecting to kfe-console..." >&2
-        ssh -t kfe-console "IS_REMOTE_SSH=1 $EXE --camerapv '$CAMPVFULL' --instrument '$hutch' --pvlist '$PVLIST' --rate '$RATE' ; bash"
-        exit_status=$?
-        echo "SSH exit status: $exit_status" >&2
-        exit $exit_status
-    elif [[ ("$hutch" == "lfe" || "$hutch" == "xrt") && "$current_host" != "lfe-console" && "$current_host" != "xbdo-control" ]]; then
-        echo "Not in SSH, connecting to lfe-console..." >&2
-        ssh -t lfe-console "IS_REMOTE_SSH=1 $EXE --camerapv '$CAMPVFULL' --instrument '$hutch' --pvlist '$PVLIST' --rate '$RATE' ; bash"
-        exit_status=$?
-        echo "SSH exit status: $exit_status" >&2
-        exit $exit_status
+# we do not have write permissions for the XTCAV camera _and_ 
+# the Acquire_RBV is 0 even when the camera is runnig
+if [ $CAMNAME != 'XTCAV' ]; then
+    IS_ACQUIRING=$(caget -t -n "$CAMPVFULL":Acquire_RBV)
+    if isNum "$IS_ACQUIRING"; then
+        if [ "$IS_ACQUIRING" -eq 0 ]; then
+            echo 'start acquiring for camera ' "$CAMNAME"
+            caput -n "$CAMPVFULL":Acquire 1
+        fi
+    else
+        echo 'cannot check Acquiring PV, try to open camera viewer anyways for ' "$CAMNAME"
     fi
 fi
 
-# If we reach this point, we're either in an SSH session, or we don't need to SSH.
-# Now, execute the camviewer.
-if [ "$RATE" -gt 0 ]; then
-    echo "$EXE" --camerapv "$CAMPVFULL" --instrument "$hutch" --pvlist "$PVLIST" --rate "$RATE"&
-    "$EXE" --camerapv "$CAMPVFULL" --instrument  "$hutch" --pvlist "$PVLIST" --rate "$RATE"&
-else
-    echo "$EXE" --camerapv "$CAMPVFULL" --instrument "$hutch" --pvlist "$PVLIST" &
-    "$EXE" --camerapv "$CAMPVFULL" --instrument  "$hutch" --pvlist "$PVLIST" &
-fi
+#XTCAV will always come over a gateway, do not ssh.
+#if [[ -z "$IS_REMOTE_SSH" && $CAMNAME != 'XTCAV' ]]; then
+#    current_host="$(hostname)"
+#    if [[ "$hutch" == "kfe" && "$current_host" != "kfe-console" && "$current_host" != "xbdo-control" ]]; then
+#        echo "Not in SSH, connecting to kfe-console..." >&2
+#        ssh -t kfe-console "IS_REMOTE_SSH=1 $EXE --camerapv '$CAMPVFULL' --instrument '$hutch' --pvlist '$PVLIST' ; bash"
+#        exit_status=$?
+#        echo "SSH exit status: $exit_status" >&2
+#        exit $exit_status
+#    elif [[ ("$hutch" == "lfe" || "$hutch" == "xrt") && "$current_host" != "lfe-console" && "$current_host" != "xbdo-control" ]]; then
+#        echo "Not in SSH, connecting to lfe-console..." >&2
+#        ssh -t lfe-console "IS_REMOTE_SSH=1 $EXE --camerapv '$CAMPVFULL' --instrument '$hutch' --pvlist '$PVLIST' ; bash"
+#        exit_status=$?
+#        echo "SSH exit status: $exit_status" >&2
+#        exit $exit_status
+#    fi
+#fi
+
+echo "$EXE" --camerapv "$CAMPVFULL" --instrument "$hutch" --pvlist "$PVLIST"
+"$EXE" --camerapv "$CAMPVFULL" --instrument  "$hutch" --pvlist "$PVLIST"
+
