Running shfmt on everything

diff --git a/scripts/get_curr_exp b/scripts/get_curr_exp
--- a/scripts/get_curr_exp
+++ b/scripts/get_curr_exp
@@ -1,7 +1,7 @@
 #!/bin/bash
 usage()
 {
-cat << EOF
+    cat << EOF
 usage: $0 options
 
 OPTIONS:
@@ -12,27 +12,26 @@ EOF
 INSTRUMENT='xxx'
 
 if [[ ($1 == "--help") || ($1 == "-h") ]]; then
-	usage
-	exit 0
+    usage
+    exit 0
 fi
 
-while getopts "H:i:le" OPTION
-do
+while getopts "H:i:le" OPTION; do
     case $OPTION in
-	i)
-	    INSTRUMENT=$OPTARG
-	    ;;
-	H)
-	    INSTRUMENT=$OPTARG
-	    ;;
-	?)
-	    usage
-	    exit
-	    ;;
-	esac
+        i)
+            INSTRUMENT=$OPTARG
+            ;;
+        H)
+            INSTRUMENT=$OPTARG
+            ;;
+        ?)
+            usage
+            exit
+            ;;
+    esac
 done
 
-DIRTMP=$(dirname  "${BASH_SOURCE[0]}")
+DIRTMP=$(dirname "${BASH_SOURCE[0]}")
 DIR=$(cd "$DIRTMP" && pwd -P)
 PATH=$PATH:$DIR
 
@@ -41,13 +40,13 @@ if [[ $INSTRUMENT != 'xxx' ]]; then
 else
     CURR_EXP=$(get_info --exp)
     if [[ $CURR_EXP == 'unknown_hutch' ]]; then
-	echo 'Cannot autodetermine hutch, for which hutch would you like to get this information?'
-	read -rt 5 hutch
-	if [[ $hutch == '' ]]; then
-	    echo 'no response, will quit'
-	    exit 1
-	fi
-	CURR_EXP=$(get_info --hutch "${hutch^^}" --exp)
+        echo 'Cannot autodetermine hutch, for which hutch would you like to get this information?'
+        read -rt 5 hutch
+        if [[ $hutch == '' ]]; then
+            echo 'no response, will quit'
+            exit 1
+        fi
+        CURR_EXP=$(get_info --hutch "${hutch^^}" --exp)
     fi
 fi
 
diff --git a/scripts/ioctool b/scripts/ioctool
--- a/scripts/ioctool
+++ b/scripts/ioctool
@@ -1,121 +1,123 @@
 #!/bin/bash
 
-function iocfpv {
-   ioc=""
-   ioc=$(grep_pv "$1" | cut -d'/' -f5 -s)
-   if [ -z "$ioc" ]; then
-      echo "Did not find an ioc associated with this PV." >&2
-      exit 1
-   elif [[ $ioc = *[[:space:]]* ]]; then # multiple iocs found if space present
-      ioccount=$(echo "$ioc" | wc -w)
-      echo "$1 is found in $ioccount places"
-      echo "Which ioc do you care about here? (press enter to exit)"
-      printf '%s\n' "$ioc" >&2
-      read -r chosenioc
-      if [[ -z "$chosenioc" ]]; then
-         echo "No ioc chosen. Exiting..." >&2
-         exit 0
-      fi
-      ioc=$chosenioc
-   fi
+function iocfpv
+{
+    ioc=""
+    ioc=$(grep_pv "$1" | cut -d'/' -f5 -s)
+    if [ -z "$ioc" ]; then
+        echo "Did not find an ioc associated with this PV." >&2
+        exit 1
+    elif [[ $ioc == *[[:space:]]* ]]; then # multiple iocs found if space present
+        ioccount=$(echo "$ioc" | wc -w)
+        echo "$1 is found in $ioccount places"
+        echo "Which ioc do you care about here? (press enter to exit)"
+        printf '%s\n' "$ioc" >&2
+        read -r chosenioc
+        if [[ -z $chosenioc ]]; then
+            echo "No ioc chosen. Exiting..." >&2
+            exit 0
+        fi
+        ioc=$chosenioc
+    fi
 
 }
 
-function iocdir {
-   ioc=$1
-   iocpath=""
-   iocpath=$(grep_ioc "$ioc" all | grep "id:'$ioc'" | sed -n "s/^.*dir: '\(\S*\)'.*$/\1/p");
-   if [[ -z $iocpath ]]; then
-      echo "Did not find ${ioc} running anywhere. Exiting..." >&2
-      exit 1
-   fi
+function iocdir
+{
+    ioc=$1
+    iocpath=""
+    iocpath=$(grep_ioc "$ioc" all | grep "id:'$ioc'" | sed -n "s/^.*dir: '\(\S*\)'.*$/\1/p")
+    if [[ -z $iocpath ]]; then
+        echo "Did not find ${ioc} running anywhere. Exiting..." >&2
+        exit 1
+    fi
 
-   if [[ ! $iocpath =~ ^/.* ]]; then
-      iocpath=/reg/g/pcds/epics/"${iocpath}"
-   fi
-
-}
-
-function ioccfg {
-   iocdir "$1"
-   iocfile=$(find "${iocpath}" -name "$1.cfg")
-   if [ -z  "$iocfile" ]; then
-      iocfile=$(find "${iocpath}" -path "*$1/st.cmd")
-      if [ -z "$iocfile" ]; then
-         echo "No files found for ioc $1" >&2
-         exit 1
-      fi
-   fi
+    if [[ ! $iocpath =~ ^/.* ]]; then
+        iocpath=/reg/g/pcds/epics/"${iocpath}"
+    fi
 
 }
 
+function ioccfg
+{
+    iocdir "$1"
+    iocfile=$(find "${iocpath}" -name "$1.cfg")
+    if [ -z "$iocfile" ]; then
+        iocfile=$(find "${iocpath}" -path "*$1/st.cmd")
+        if [ -z "$iocfile" ]; then
+            echo "No files found for ioc $1" >&2
+            exit 1
+        fi
+    fi
 
-function camname_to_pv {
-   #A function that will loop through camviewer.cfg files throughout all hutches to find the name then use that to search for its PV
-   campv=""
-   hutch="$1"
-   if [ "$1" == "" ]; then
-      hutch=$(get_info --gethutch)
-      if [[ "$hutch" == unknown_hutch ]]; then
-         echo 'unknown hutch, specify using the -H/--hutch option'
-         usage
-         exit 1
-      fi
-   fi
-
-   VIEWERCFG=/reg/g/pcds/pyps/config/$hutch/camviewer.cfg
-   CAMNAME=$(echo "$2" | sed -e 's/-/ /g' -e 's/_/ /g' -e 's/ /[-_ ]/g')
-
-
-
-   # The story here:
-   # See how many matches we have in the hutch.
-   # If 0, try looking in all of the hutches.
-   # If 1, then we're done.
-   # Otherwise:
-   # Look for a complete match, anchored on both sides.
-   # Look for a match anchored at the end.
-   # If there is more than one, return "ambiguous"
-   #
-   # Make a temp file with just the PVs and camera names that match.
-   tmp=/tmp/cv.$$
-   grep -i "$CAMNAME" "$VIEWERCFG" | grep -v '#' | awk -F, '{ if (split($2,a,";")==1) n=$2; else n=a[2]; gsub(" ","",n); gsub(" ","",$4); printf "%s %s\n", n, $4; }' >$tmp
-   c=$(wc -l <$tmp)
-   if [ "$c" -eq 0 ]; then
-       VIEWERCFG="/reg/g/pcds/pyps/config/*/camviewer.cfg"
-       grep -i "$CAMNAME" "$VIEWERCFG" | grep -v '#' | awk -F, '{ if (split($2,a,";")==1) n=$2; else n=a[2]; gsub(" ","",n); gsub(" ","",$4); printf "%s %s\n", n, $4; }' >$tmp
-       c=$(wc -l <$tmp)
-       if [ "$c" -eq 0 ]; then
-           echo "No match for $2"
-           rm -f $tmp
-           exit
-       fi
-   fi
-   if [ "$c" -eq 1 ]; then
-      campv=$(awk '{print $1;}' <$tmp)
-      rm -f $tmp
-      return
-   fi
-   # OK, ambiguous.  Look for a complete match on the second word.
-   if [ "$(grep -E -i -c "$CAMNAME\$" < $tmp)" -eq 1 ]; then
-      campv=$(grep -E -i "$CAMNAME\$" < $tmp | awk '{print $1;}')
-      rm -f $tmp
-      return
-   fi
-   # What about just a match at the end? (That is, if we are searching
-   # for "yag1", prefer "mec_yag1" to "mec_yag11".)
-   if [ "$(grep -E -i -c "$CAMNAME\$" < $tmp)" -eq 1 ]; then
-      campv=$(grep -E -i "$CAMNAME\$" < $tmp | awk '{print $1;}')
-      rm -f $tmp
-      return
-   fi
-   echo '"'"$2"'" is ambiguous:'
-   rm -f $tmp
-   exit
 }
 
-usage(){
-cat << EOF
+function camname_to_pv
+{
+    #A function that will loop through camviewer.cfg files throughout all hutches to find the name then use that to search for its PV
+    campv=""
+    hutch="$1"
+    if [ "$1" == "" ]; then
+        hutch=$(get_info --gethutch)
+        if [[ $hutch == unknown_hutch ]]; then
+            echo 'unknown hutch, specify using the -H/--hutch option'
+            usage
+            exit 1
+        fi
+    fi
+
+    VIEWERCFG=/reg/g/pcds/pyps/config/$hutch/camviewer.cfg
+    CAMNAME=$(echo "$2" | sed -e 's/-/ /g' -e 's/_/ /g' -e 's/ /[-_ ]/g')
+
+    # The story here:
+    # See how many matches we have in the hutch.
+    # If 0, try looking in all of the hutches.
+    # If 1, then we're done.
+    # Otherwise:
+    # Look for a complete match, anchored on both sides.
+    # Look for a match anchored at the end.
+    # If there is more than one, return "ambiguous"
+    #
+    # Make a temp file with just the PVs and camera names that match.
+    tmp=/tmp/cv.$$
+    grep -i "$CAMNAME" "$VIEWERCFG" | grep -v '#' | awk -F, '{ if (split($2,a,";")==1) n=$2; else n=a[2]; gsub(" ","",n); gsub(" ","",$4); printf "%s %s\n", n, $4; }' > $tmp
+    c=$(wc -l < $tmp)
+    if [ "$c" -eq 0 ]; then
+        VIEWERCFG="/reg/g/pcds/pyps/config/*/camviewer.cfg"
+        grep -i "$CAMNAME" "$VIEWERCFG" | grep -v '#' | awk -F, '{ if (split($2,a,";")==1) n=$2; else n=a[2]; gsub(" ","",n); gsub(" ","",$4); printf "%s %s\n", n, $4; }' > $tmp
+        c=$(wc -l < $tmp)
+        if [ "$c" -eq 0 ]; then
+            echo "No match for $2"
+            rm -f $tmp
+            exit
+        fi
+    fi
+    if [ "$c" -eq 1 ]; then
+        campv=$(awk '{print $1;}' < $tmp)
+        rm -f $tmp
+        return
+    fi
+    # OK, ambiguous.  Look for a complete match on the second word.
+    if [ "$(grep -E -i -c "$CAMNAME\$" < $tmp)" -eq 1 ]; then
+        campv=$(grep -E -i "$CAMNAME\$" < $tmp | awk '{print $1;}')
+        rm -f $tmp
+        return
+    fi
+    # What about just a match at the end? (That is, if we are searching
+    # for "yag1", prefer "mec_yag1" to "mec_yag11".)
+    if [ "$(grep -E -i -c "$CAMNAME\$" < $tmp)" -eq 1 ]; then
+        campv=$(grep -E -i "$CAMNAME\$" < $tmp | awk '{print $1;}')
+        rm -f $tmp
+        return
+    fi
+    echo '"'"$2"'" is ambiguous:'
+    rm -f $tmp
+    exit
+}
+
+usage()
+{
+    cat << EOF
 usage: $0 <ioc>|<pv>|<camera name> [option]
 
 Script that returns information about an ioc given its name, PV, or camera name
@@ -137,45 +139,42 @@ pvs      : opens the IOC.pvlist file in less
 EOF
 }
 
-
 if [[ ($1 == "--help") || ($1 == "-h") ]]; then
-   usage
-   exit 0
+    usage
+    exit 0
 fi
 
 if OPTIONS=$(getopt -o H: --long hutch: -n \'"$0"\' -- "$@"); then
-   echo "Terminating..." >&2
-   exit 1
+    echo "Terminating..." >&2
+    exit 1
 fi
 
 eval set -- "$OPTIONS"
 
-while true
-do
-   case "$1" in
-      -H|--hutch)
-         hutch=$2
-         shift 2
-         ;;
-      ?)
-         break
-         ;;
-      --)
-         shift
-         break
-         ;;
-      *)
-         echo "Internal Error"
-         exit 1
-         ;;
-   esac
+while true; do
+    case "$1" in
+        -H | --hutch)
+            hutch=$2
+            shift 2
+            ;;
+        ?)
+            break
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Internal Error"
+            exit 1
+            ;;
+    esac
 done
 
-
 if [ $# -lt 1 ]; then
-   echo 'need arguments: input ioc or pv name' >&2
-   usage
-   exit 1
+    echo 'need arguments: input ioc or pv name' >&2
+    usage
+    exit 1
 fi
 
 NAME=$1
@@ -184,9 +183,8 @@ CMD=$2
 #################################################################
 
 if [[ $NAME == *':'* ]]; then #we are assuming that PVs have a colon in them
-   iocfpv "$NAME"
-   NAME="$ioc"
-
+    iocfpv "$NAME"
+    NAME="$ioc"
 
 #This elif block applies to the variety of camera names(e.g. TMO-07, xcs_gige_5, or IM2K4)
 #1) Check to see if the name has an underscore, dash, or only numbers and letters. If it doesn't return "unmatched format"
@@ -194,124 +192,122 @@ if [[ $NAME == *':'* ]]; then #we are assuming that PVs have a colon in them
 #3) If that returns nothing, try converting the camera name to a PV and search for that
 #4) If neither of those produce results return "Did not find name anywhere"
 elif [[ $NAME == *'-'* || $NAME == *'_'* || $NAME =~ ^[[:alnum:]]+$ ]]; then
-   INFO=$(grep_ioc "$NAME" all | grep "id:'$NAME'")
-      if [ -z "$INFO" ]; then
-         #echo "Hutch = $hutch"
-         camname_to_pv "$hutch" "$NAME"
-         iocfpv "$campv"
-         NAME="$ioc"
+    INFO=$(grep_ioc "$NAME" all | grep "id:'$NAME'")
+    if [ -z "$INFO" ]; then
+        #echo "Hutch = $hutch"
+        camname_to_pv "$hutch" "$NAME"
+        iocfpv "$campv"
+        NAME="$ioc"
 
-      elif [[ -z "$NAME" ]]; then
-         echo "Did not find ${NAME} running anywhere. Exiting..." >&2
-         exit 1
-      fi
+    elif [[ -z $NAME ]]; then
+        echo "Did not find ${NAME} running anywhere. Exiting..." >&2
+        exit 1
+    fi
 
-elif [[ ! $NAME == *'-'* ]]; then #We are assuming that ioc names contain a dash in them
-   echo "${NAME} does not match the format for PVs or IOC names. Exiting..." >&2
-   exit 1
+elif [[ $NAME != *'-'* ]]; then #We are assuming that ioc names contain a dash in them
+    echo "${NAME} does not match the format for PVs or IOC names. Exiting..." >&2
+    exit 1
 fi
-
 
 #################################################################
 
 if [ "$CMD" == "name" ] || [ "$CMD" == "" ]; then
-   echo "$NAME"
+    echo "$NAME"
 
 #################################################################
 
-elif [ "$CMD" ==  "dir" ]; then
-   iocdir "$NAME"
-   echo "$iocpath"
+elif [ "$CMD" == "dir" ]; then
+    iocdir "$NAME"
+    echo "$iocpath"
 
 #################################################################
 
 elif [ "$CMD" == "cddir" ]; then
-   iocdir "$NAME"
-   if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
-      echo "Script is not being sourced. Start with 'source $0' before calling script with this option." >&2
-      exit 1
-   fi
-   cd "${iocpath}"
-
+    iocdir "$NAME"
+    if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
+        echo "Script is not being sourced. Start with 'source $0' before calling script with this option." >&2
+        exit 1
+    fi
+    cd "${iocpath}"
 
 #################################################################
 
 elif [ "$CMD" == "cfg" ]; then
-   ioccfg "$NAME"
-   echo "$iocfile"
+    ioccfg "$NAME"
+    echo "$iocfile"
 
 #################################################################
 
 elif [ "$CMD" == "less" ]; then
-   ioccfg "$NAME"
-   less "$iocfile"
+    ioccfg "$NAME"
+    less "$iocfile"
 
 #################################################################
 
 elif [ "$CMD" == "cat" ]; then
-   ioccfg "$NAME"
-   cat "$iocfile"
+    ioccfg "$NAME"
+    cat "$iocfile"
 
 #################################################################
 
 elif [ "$CMD" == "data" ]; then
-   iocdatapath=/reg/d/iocData/"${NAME}"/iocInfo
-   if [ -d "$iocdatapath" ]; then
-      echo "${iocdatapath}"
-   else
-      echo "$iocdatapath could not be found. Exiting..." >&2
-   fi
+    iocdatapath=/reg/d/iocData/"${NAME}"/iocInfo
+    if [ -d "$iocdatapath" ]; then
+        echo "${iocdatapath}"
+    else
+        echo "$iocdatapath could not be found. Exiting..." >&2
+    fi
 
 #################################################################
 
 elif [ "$CMD" == "autosave" ]; then
-   autosavefile=/reg/d/iocData/"${NAME}"/autosave/${NAME}.sav
-   if [ -f "$autosavefile" ]; then
-      less "$autosavefile"
-   else
-      echo "Recent autosave file could not be found." >&2
-   fi
+    autosavefile=/reg/d/iocData/"${NAME}"/autosave/${NAME}.sav
+    if [ -f "$autosavefile" ]; then
+        less "$autosavefile"
+    else
+        echo "Recent autosave file could not be found." >&2
+    fi
 
 #################################################################
 
 elif [ "$CMD" == "archive" ]; then
-   archivefile=/reg/d/iocData/"${NAME}"/archive/${NAME}.archive
-   if [ -f "$archivefile" ]; then
-      less "$archivefile"
-   else
-      echo "Archive file could not be found." >&2
-   fi
+    archivefile=/reg/d/iocData/"${NAME}"/archive/${NAME}.archive
+    if [ -f "$archivefile" ]; then
+        less "$archivefile"
+    else
+        echo "Archive file could not be found." >&2
+    fi
 
 #################################################################
 
 elif [ "$CMD" == "log" ]; then
-   logfile=/reg/d/iocData/"${NAME}"/iocInfo/ioc.log
-   if [ -f "$logfile" ]; then
-      less "$logfile"
-   else
-      echo "Recent log file could not be found." >&2
-   fi
+    logfile=/reg/d/iocData/"${NAME}"/iocInfo/ioc.log
+    if [ -f "$logfile" ]; then
+        less "$logfile"
+    else
+        echo "Recent log file could not be found." >&2
+    fi
 
 #################################################################
 
 elif [ "$CMD" == "telnet" ]; then
-   INFO=$(grep_ioc "$NAME" all | grep "id:'$NAME'")
-   if [ -z "$INFO" ]; then
-      echo "$NAME could not be found. Exiting..." >&2
-      exit 1
-   fi
-   HOST=$(echo "$INFO" | sed -n "s/^.*host: '\(\S*\)'.*$/\1/p")
-   PORT=$(echo "$INFO" | sed -n "s/^.*port: \(\S*\),.*$/\1/p")
-   echo "$HOST":"$PORT"
-   telnet "$HOST" "$PORT"
+    INFO=$(grep_ioc "$NAME" all | grep "id:'$NAME'")
+    if [ -z "$INFO" ]; then
+        echo "$NAME could not be found. Exiting..." >&2
+        exit 1
+    fi
+    HOST=$(echo "$INFO" | sed -n "s/^.*host: '\(\S*\)'.*$/\1/p")
+    PORT=$(echo "$INFO" | sed -n "s/^.*port: \(\S*\),.*$/\1/p")
+    echo "$HOST":"$PORT"
+    telnet "$HOST" "$PORT"
 
 #################################################################
 
 elif [ "$CMD" == "pvs" ]; then
-   pvlistfile=/cds/data/iocData/"${NAME}"/iocInfo/IOC.pvlist
-   if [ -f "$pvlistfile" ]; then
-      less "$pvlistfile"
-   else
-      echo "$pvlistfile could not be found." >&2
-   fi
+    pvlistfile=/cds/data/iocData/"${NAME}"/iocInfo/IOC.pvlist
+    if [ -f "$pvlistfile" ]; then
+        less "$pvlistfile"
+    else
+        echo "$pvlistfile could not be found." >&2
+    fi
 fi
diff --git a/scripts/ipmConfigEpics b/scripts/ipmConfigEpics
--- a/scripts/ipmConfigEpics
+++ b/scripts/ipmConfigEpics
@@ -15,231 +15,231 @@ lfeIpm='um6_ipm hfxdg2_ipm pim3m'
 
 ipmList()
 {
-printf 'Possible boxes:\n'
-if [[ $hutch == 'xcs' ]]; then
-   for box in $hx2Ipm $um6Ipm $dg2Ipm $xcsIpm; do echo "$box"; done
-elif [[ $hutch == 'xpp' ]]; then
-   for box in $hx2Ipm $xppIpm; do echo "$box"; done
-elif [[ $hutch == 'cxi' ]]; then
-   for box in $hx2Ipm $um6Ipm $dg2Ipm $cxiIpm; do echo "$box"; done
-elif [[ $hutch == 'mfx' ]]; then
-   for box in $hx2Ipm $um6Ipm $mfxIpm; do echo "$box"; done
-elif [[ $hutch == 'mec' ]]; then
-   for box in $hx2Ipm $um6Ipm $mecIpm; do echo "$box"; done
-elif [[ $hutch == 'lfe' ]]; then
-   for box in $lfeIpm; do echo "$box"; done
-else
-    echo 'hutch cannot be determined, quit'
-    exit
-fi
+    printf 'Possible boxes:\n'
+    if [[ $hutch == 'xcs' ]]; then
+        for box in $hx2Ipm $um6Ipm $dg2Ipm $xcsIpm; do echo "$box"; done
+    elif [[ $hutch == 'xpp' ]]; then
+        for box in $hx2Ipm $xppIpm; do echo "$box"; done
+    elif [[ $hutch == 'cxi' ]]; then
+        for box in $hx2Ipm $um6Ipm $dg2Ipm $cxiIpm; do echo "$box"; done
+    elif [[ $hutch == 'mfx' ]]; then
+        for box in $hx2Ipm $um6Ipm $mfxIpm; do echo "$box"; done
+    elif [[ $hutch == 'mec' ]]; then
+        for box in $hx2Ipm $um6Ipm $mecIpm; do echo "$box"; done
+    elif [[ $hutch == 'lfe' ]]; then
+        for box in $lfeIpm; do echo "$box"; done
+    else
+        echo 'hutch cannot be determined, quit'
+        exit
+    fi
 }
 
 ipmSetEnvPars()
 {
-if [ $# -lt 1 ]; then
-    echo 'need one arguments: boxname'
-    exit
-fi
+    if [ $# -lt 1 ]; then
+        echo 'need one arguments: boxname'
+        exit
+    fi
 
-# Shared IPMs
-if [[ $1 == 'hx2_ipm' ]]; then
-    IOC="IOC:HX2:SB1:BMMON"
-    BASE='HX2:SB1:BMMON'
-    EVR='HX2:SB1:BMMON:EVR'
-    WAVE8='hx2_ipm'
-elif [[ $1 == 'um6_ipm' ]]; then        #aka xcs ipm1
-    BASE="XCS:DG1:IMB:01"
-    IOC="XCS:R04:IOC:34"
-    EVR="XCS:R04:EVR:34"
-elif [[ $1 == 'um6_dio' ]]; then	#aka xcs ipm1
-    BASE="XCS:DG1:IMB:02"
-    IOC="XCS:R04:IOC:34"
-    EVR="XCS:R04:EVR:34"
-elif [[ $1 == 'hfxdg2_ipm' ]]; then	#aka xcs ipm2
-    IOC="IOC:HFX:DG2:BMMON"
-    BASE='HFX:DG2:BMMON'
-    EVR='HFX:DG2:BMMON:EVR'
-    WAVE8='hfxipm'
-elif [[ $1 == 'pim3m' ]]; then
-    BASE="HFX:DG3:IMB:02"
-    IOC="XCS:R38:IOC:43"
-    EVR="XCS:R38:EVR:43"
-fi
+    # Shared IPMs
+    if [[ $1 == 'hx2_ipm' ]]; then
+        IOC="IOC:HX2:SB1:BMMON"
+        BASE='HX2:SB1:BMMON'
+        EVR='HX2:SB1:BMMON:EVR'
+        WAVE8='hx2_ipm'
+    elif [[ $1 == 'um6_ipm' ]]; then #aka xcs ipm1
+        BASE="XCS:DG1:IMB:01"
+        IOC="XCS:R04:IOC:34"
+        EVR="XCS:R04:EVR:34"
+    elif [[ $1 == 'um6_dio' ]]; then #aka xcs ipm1
+        BASE="XCS:DG1:IMB:02"
+        IOC="XCS:R04:IOC:34"
+        EVR="XCS:R04:EVR:34"
+    elif [[ $1 == 'hfxdg2_ipm' ]]; then #aka xcs ipm2
+        IOC="IOC:HFX:DG2:BMMON"
+        BASE='HFX:DG2:BMMON'
+        EVR='HFX:DG2:BMMON:EVR'
+        WAVE8='hfxipm'
+    elif [[ $1 == 'pim3m' ]]; then
+        BASE="HFX:DG3:IMB:02"
+        IOC="XCS:R38:IOC:43"
+        EVR="XCS:R38:EVR:43"
+    fi
 
-# Hutch-specific IPMs
-if [[ $hutch == 'xcs' ]]; then
-    if [[ $1 == 'decmono' ]]; then
-	BASE="HFX:MON:IMB:03"
-	IOC="XCS:R38:IOC:43"
-	EVR="XCS:R38:EVR:43"
-    elif [[ $1 == 'diomono' ]]; then
-	BASE="HFX:MON:IMB:02"
-	IOC="XCS:R38:IOC:43"
-	EVR="XCS:R38:EVR:43"
-    elif [[ $1 == 'ipmmono' ]]; then
-	BASE="HFX:MON:IMB:01"
-	IOC="XCS:R38:IOC:43"
-	EVR="XCS:R38:EVR:43"
-    elif [[ $1 == 'pim3' ]]; then
-	BASE="XCS:DG3:IMB:04"
-	IOC="XCS:R38:IOC:43"
-	EVR="XCS:R38:EVR:43"
-    elif [[ $1 == 'ipm3' ]]; then
-	BASE="XCS:DG3:IMB:03"
-	IOC="XCS:R38:IOC:43"
-	EVR="XCS:R38:EVR:43"
-    elif [[ $1 == 'ipm4' ]]; then
-	IOC="IOC:XCS:SB1:BMMON"
-	BASE='XCS:SB1:BMMON'
-	EVR='XCS:SB1:BMMON:EVR'
-	WAVE8='sb1bmmon'
-    elif [[ $1 == 'pim4' ]]; then
-	BASE="XCS:SB1:IMB:02"
-	IOC="IOC:XCS:IPM"
-	EVR="XCS:R44:EVR:01"
-    elif [[ $1 == 'ipm5' ]]; then
-	IOC="IOC:XCS:SB2:BMMON"
-	BASE='XCS:SB2:BMMON'
-	EVR='XCS:SB2:BMMON:EVR'
-	WAVE8='sb2bmmon'
-    elif [[ $1 == 'pim5' ]]; then
-	BASE="XCS:SB2:IMB:02"
-	IOC="IOC:XCS:IPM"
-	EVR="XCS:R44:EVR:01"
-    elif [[ $1 == 'ipmgonLD' ]]; then
-	BASE="XCS:USR:IMB:01"
-	IOC="IOC:XCS:USR:IPM"
-	EVR="XCS:R42:EVR:01"
-    elif [[ $1 == 'ipmlamLD' ]]; then
-	BASE="XCS:LAM:IMB:02"
-	IOC="IOC:XCS:IPM"
-	EVR="XCS:R44:EVR:01"
-    elif [[ $1 == 'snddio' ]]; then
-	IOC="IOC:XCS:SND:DIO"
-	BASE='XCS:SND:DIO'
-	EVR='XCS:SND:DIO:EVR'
-	WAVE8='snddio'
+    # Hutch-specific IPMs
+    if [[ $hutch == 'xcs' ]]; then
+        if [[ $1 == 'decmono' ]]; then
+            BASE="HFX:MON:IMB:03"
+            IOC="XCS:R38:IOC:43"
+            EVR="XCS:R38:EVR:43"
+        elif [[ $1 == 'diomono' ]]; then
+            BASE="HFX:MON:IMB:02"
+            IOC="XCS:R38:IOC:43"
+            EVR="XCS:R38:EVR:43"
+        elif [[ $1 == 'ipmmono' ]]; then
+            BASE="HFX:MON:IMB:01"
+            IOC="XCS:R38:IOC:43"
+            EVR="XCS:R38:EVR:43"
+        elif [[ $1 == 'pim3' ]]; then
+            BASE="XCS:DG3:IMB:04"
+            IOC="XCS:R38:IOC:43"
+            EVR="XCS:R38:EVR:43"
+        elif [[ $1 == 'ipm3' ]]; then
+            BASE="XCS:DG3:IMB:03"
+            IOC="XCS:R38:IOC:43"
+            EVR="XCS:R38:EVR:43"
+        elif [[ $1 == 'ipm4' ]]; then
+            IOC="IOC:XCS:SB1:BMMON"
+            BASE='XCS:SB1:BMMON'
+            EVR='XCS:SB1:BMMON:EVR'
+            WAVE8='sb1bmmon'
+        elif [[ $1 == 'pim4' ]]; then
+            BASE="XCS:SB1:IMB:02"
+            IOC="IOC:XCS:IPM"
+            EVR="XCS:R44:EVR:01"
+        elif [[ $1 == 'ipm5' ]]; then
+            IOC="IOC:XCS:SB2:BMMON"
+            BASE='XCS:SB2:BMMON'
+            EVR='XCS:SB2:BMMON:EVR'
+            WAVE8='sb2bmmon'
+        elif [[ $1 == 'pim5' ]]; then
+            BASE="XCS:SB2:IMB:02"
+            IOC="IOC:XCS:IPM"
+            EVR="XCS:R44:EVR:01"
+        elif [[ $1 == 'ipmgonLD' ]]; then
+            BASE="XCS:USR:IMB:01"
+            IOC="IOC:XCS:USR:IPM"
+            EVR="XCS:R42:EVR:01"
+        elif [[ $1 == 'ipmlamLD' ]]; then
+            BASE="XCS:LAM:IMB:02"
+            IOC="IOC:XCS:IPM"
+            EVR="XCS:R44:EVR:01"
+        elif [[ $1 == 'snddio' ]]; then
+            IOC="IOC:XCS:SND:DIO"
+            BASE='XCS:SND:DIO'
+            EVR='XCS:SND:DIO:EVR'
+            WAVE8='snddio'
+        fi
+    elif [[ $hutch == 'cxi' ]]; then
+        if [[ $1 == 'dg2ipm' ]]; then
+            IOC="IOC:CXI:DG2:BMMON"
+            BASE='CXI:DG2:BMMON'
+            EVR='CXI:DG2:BMMON:EVR'
+            WAVE8='dg2ipm'
+        elif [[ $1 == 'dg3ipm' ]]; then
+            IOC="IOC:CXI:DG3:BMMON"
+            BASE='CXI:DG3:BMMON'
+            EVR='CXI:DG3:BMMON:EVR'
+            WAVE8='dg3ipm'
+        elif [[ $1 == 'usrdio' ]]; then
+            IOC="IOC:CXI:USR:DIO"
+            BASE='CXI:USR:DIO'
+            EVR='CXI:USR:DIO:EVR'
+            WAVE8='usrdio'
+        fi
+    elif [[ $hutch == 'mfx' ]]; then
+        if [[ $1 == 'dg1ipm' ]]; then
+            IOC="IOC:MFX:DG1:BMMON"
+            BASE='MFX:DG1:BMMON'
+            EVR='MFX:DG1:BMMON:EVR'
+            WAVE8='dg1ipm'
+        elif [[ $1 == 'dg2ipm' ]]; then
+            IOC="IOC:MFX:DG2:BMMON"
+            BASE='MFX:DG2:BMMON'
+            EVR='MFX:DG2:BMMON:EVR'
+            WAVE8='dg2ipm'
+        elif [[ $1 == 'usrdio' ]]; then
+            IOC="IOC:MFX:USR:DIO"
+            BASE='MFX:USR:DIO'
+            EVR='MFX:USR:DIO:EVR'
+            WAVE8='usrdio'
+        fi
+    elif [[ $hutch == 'xpp' ]]; then
+        if [[ $1 == 'diomono' ]]; then
+            IOC="IOC:XPP:IPM"
+            BASE='XPP:MON:IPM:02'
+            EVR='XPP:IPM:EVR'
+        elif [[ $1 == 'decmono' ]]; then
+            IOC="IOC:XPP:IPM"
+            BASE='XPP:MON:IPM:01'
+            EVR='XPP:IPM:EVR'
+        elif [[ $1 == 'ipm2' ]]; then
+            IOC="IOC:XPP:SB2:BMMON"
+            BASE='XPP:SB2:BMMON'
+            EVR='XPP:SB2:BMMON:EVR'
+            WAVE8='sb2bmmon'
+        elif [[ $1 == 'ipm3' ]]; then
+            IOC="IOC:XPP:SB3:BMMON"
+            BASE='XPP:SB3:BMMON'
+            EVR='XPP:SB3:BMMON:EVR'
+            WAVE8='sb3bmmon'
+        elif [[ $1 == 'pim3' ]]; then
+            IOC="IOC:XPP:IPM"
+            BASE='XPP:SB3:IPM:02'
+            EVR='XPP:IPM:EVR'
+        elif [[ $1 == 'diodeU' ]]; then
+            IOC="IOC:XPP:IPM"
+            BASE='XPP:USR:IPM:01'
+            EVR='XPP:IPM:EVR'
+        fi
+    elif [[ $hutch == 'mec' ]]; then
+        if [[ $1 == 'ipm1' ]]; then
+            IOC="XRT:R33:IOC:39"
+            BASE='MEC:HXM:IPM:01'
+            EVR='XRT:R44:EVR:39'
+        elif [[ $1 == 'hxm_pim' ]]; then
+            IOC="XRT:R33:IOC:39"
+            BASE='MEC:HXM:PIM:01'
+            EVR='XRT:R44:EVR:39'
+        elif [[ $1 == 'pim2' ]]; then
+            IOC="IOC:MEC:IMB02"
+            BASE='MEC:XT2:PIM:02'
+            EVR='MEC:XT2:EVR:01'
+        elif [[ $1 == 'pim3' ]]; then
+            IOC="IOC:MEC:IMB02"
+            BASE='MEC:XT2:PIM:03'
+            EVR='MEC:XT2:EVR:01'
+        elif [[ $1 == 'tc1_imb1' ]]; then
+            IOC="IOC:MEC:IPIMB01"
+            EVR='MEC:TC1:EVR:01'
+            BASE='MEC:TC1:IMB:01'
+        elif [[ $1 == 'usr_imb1' ]]; then
+            IOC="IOC:MEC:IPIMB01"
+            EVR='MEC:TC1:EVR:01'
+            BASE='MEC:USR:IMB:01'
+        elif [[ $1 == 'usr_imb2' ]]; then
+            IOC="IOC:MEC:IPIMB01"
+            EVR='MEC:TC1:EVR:01'
+            BASE='MEC:USR:IMB:02'
+        elif [[ $1 == 'las_imb1' ]]; then
+            IOC="IOC:MEC:IPIMB01"
+            EVR='MEC:TC1:EVR:01'
+            BASE='MEC:LAS:IMB:01'
+        elif [[ $1 == 'las_imb2' ]]; then
+            IOC="IOC:MEC:IPIMB01"
+            EVR='MEC:TC1:EVR:01'
+            BASE='MEC:LAS:IMB:02'
+        elif [[ $1 == 'ipm2' ]]; then
+            IOC="IOC:MEC:XT2-1:BMMON"
+            EVR="MEC:XT2-1:BMMON:EVR"
+            BASE="MEC:XT2-1:BMMON"
+            WAVE8='xt2-1bmmon'
+        elif [[ $1 == 'ipm3' ]]; then
+            IOC="IOC:MEC:XT2-2:BMMON"
+            EVR="MEC:XT2-2:BMMON:EVR"
+            BASE="MEC:XT2-2:BMMON"
+            WAVE8='xt2-2bmmon'
+        fi
     fi
-elif [[ $hutch == 'cxi' ]]; then
-    if [[ $1 == 'dg2ipm' ]]; then
-	IOC="IOC:CXI:DG2:BMMON"
-	BASE='CXI:DG2:BMMON'
-	EVR='CXI:DG2:BMMON:EVR'
-	WAVE8='dg2ipm'
-    elif [[ $1 == 'dg3ipm' ]]; then
-	IOC="IOC:CXI:DG3:BMMON"
-	BASE='CXI:DG3:BMMON'
-	EVR='CXI:DG3:BMMON:EVR'
-	WAVE8='dg3ipm'
-    elif [[ $1 == 'usrdio' ]]; then
-        IOC="IOC:CXI:USR:DIO"
-        BASE='CXI:USR:DIO'
-        EVR='CXI:USR:DIO:EVR'
-        WAVE8='usrdio'
-    fi
-elif [[ $hutch == 'mfx' ]]; then
-    if [[ $1 == 'dg1ipm' ]]; then
-	IOC="IOC:MFX:DG1:BMMON"
-	BASE='MFX:DG1:BMMON'
-	EVR='MFX:DG1:BMMON:EVR'
-	WAVE8='dg1ipm'
-    elif [[ $1 == 'dg2ipm' ]]; then
-	IOC="IOC:MFX:DG2:BMMON"
-	BASE='MFX:DG2:BMMON'
-	EVR='MFX:DG2:BMMON:EVR'
-	WAVE8='dg2ipm'
-    elif [[ $1 == 'usrdio' ]]; then
-        IOC="IOC:MFX:USR:DIO"
-        BASE='MFX:USR:DIO'
-        EVR='MFX:USR:DIO:EVR'
-        WAVE8='usrdio'
-    fi
-elif [[ $hutch == 'xpp' ]]; then
-    if [[ $1 == 'diomono' ]]; then
-	IOC="IOC:XPP:IPM"
-	BASE='XPP:MON:IPM:02'
-	EVR='XPP:IPM:EVR'
-    elif [[ $1 == 'decmono' ]]; then
-	IOC="IOC:XPP:IPM"
-	BASE='XPP:MON:IPM:01'
-	EVR='XPP:IPM:EVR'
-    elif [[ $1 == 'ipm2' ]]; then
-	IOC="IOC:XPP:SB2:BMMON"
-	BASE='XPP:SB2:BMMON'
-	EVR='XPP:SB2:BMMON:EVR'
-	WAVE8='sb2bmmon'
-    elif [[ $1 == 'ipm3' ]]; then
-	IOC="IOC:XPP:SB3:BMMON"
-	BASE='XPP:SB3:BMMON'
-	EVR='XPP:SB3:BMMON:EVR'
-	WAVE8='sb3bmmon'
-    elif [[ $1 == 'pim3' ]]; then
-	IOC="IOC:XPP:IPM"
-	BASE='XPP:SB3:IPM:02'
-	EVR='XPP:IPM:EVR'
-    elif [[ $1 == 'diodeU' ]]; then
-	IOC="IOC:XPP:IPM"
-	BASE='XPP:USR:IPM:01'
-	EVR='XPP:IPM:EVR'
-    fi
-elif [[ $hutch == 'mec' ]]; then
-    if [[ $1 == 'ipm1' ]]; then
-	IOC="XRT:R33:IOC:39"
-	BASE='MEC:HXM:IPM:01'
-	EVR='XRT:R44:EVR:39'
-    elif [[ $1 == 'hxm_pim' ]]; then
-	IOC="XRT:R33:IOC:39"
-	BASE='MEC:HXM:PIM:01'
-	EVR='XRT:R44:EVR:39'
-    elif [[ $1 == 'pim2' ]]; then
-	IOC="IOC:MEC:IMB02"
-	BASE='MEC:XT2:PIM:02'
-	EVR='MEC:XT2:EVR:01'
-    elif [[ $1 == 'pim3' ]]; then
-	IOC="IOC:MEC:IMB02"
-	BASE='MEC:XT2:PIM:03'
-	EVR='MEC:XT2:EVR:01'
-    elif [[ $1 == 'tc1_imb1' ]]; then
-	IOC="IOC:MEC:IPIMB01"
-	EVR='MEC:TC1:EVR:01'
-	BASE='MEC:TC1:IMB:01'
-    elif [[ $1 == 'usr_imb1' ]]; then
-	IOC="IOC:MEC:IPIMB01"
-	EVR='MEC:TC1:EVR:01'
-	BASE='MEC:USR:IMB:01'
-    elif [[ $1 == 'usr_imb2' ]]; then
-	IOC="IOC:MEC:IPIMB01"
-	EVR='MEC:TC1:EVR:01'
-	BASE='MEC:USR:IMB:02'
-    elif [[ $1 == 'las_imb1' ]]; then
-	IOC="IOC:MEC:IPIMB01"
-	EVR='MEC:TC1:EVR:01'
-	BASE='MEC:LAS:IMB:01'
-    elif [[ $1 == 'las_imb2' ]]; then
-	IOC="IOC:MEC:IPIMB01"
-	EVR='MEC:TC1:EVR:01'
-	BASE='MEC:LAS:IMB:02'
-    elif [[ $1 == 'ipm2' ]]; then
-	IOC="IOC:MEC:XT2-1:BMMON"
-	EVR="MEC:XT2-1:BMMON:EVR"
-	BASE="MEC:XT2-1:BMMON"
-	WAVE8='xt2-1bmmon'
-    elif [[ $1 == 'ipm3' ]]; then
-	IOC="IOC:MEC:XT2-2:BMMON"
-	EVR="MEC:XT2-2:BMMON:EVR"
-	BASE="MEC:XT2-2:BMMON"
-	WAVE8='xt2-2bmmon'
-    fi
-fi
-if [ ${#BASE} == 0 ]
-    then
+    if [ ${#BASE} == 0 ]; then
         echo 'Not a recognized boxname. Exiting...'
         exit 1
-fi
+    fi
 }
 
 # Attempt to read the :SUM PV and open a GUI if successful and exits if not. Uses wave8 or ipimb accordingly
-ipmGUI(){
+ipmGUI()
+{
     if caget "$BASE":SUM > /dev/null 2>&1; then
         if [ ${#WAVE8} -gt 0 ]; then
             /reg/g/pcds/pyps/apps/wave8/latest/wave8 --base "$BASE" --evr "$EVR" --ioc "$IOC"
@@ -252,12 +252,13 @@ ipmGUI(){
 }
 
 # Get hutch name, if not given, using get_info
-get_hutch(){
+get_hutch()
+{
     if [ -z "$HUTCH" ]; then
         hutch=$(get_info --gethutch)
-        if [[ $hutch = unknown_hutch ]]; then
-	    echo 'unknown hutch, cannot use ipmConfigEpics script'
-	    exit 1
+        if [[ $hutch == unknown_hutch ]]; then
+            echo 'unknown hutch, cannot use ipmConfigEpics script'
+            exit 1
         fi
         HUTCH=${hutch^^}
     else
@@ -267,7 +268,7 @@ get_hutch(){
 
 usage()
 {
-cat << EOF
+    cat << EOF
 usage: $0 [-b boxname] [-H hutch] [-d] [-h] [-l]
 
 Displays a GUI for the selected IPM. Running without arguments allows for box selection.
@@ -282,7 +283,8 @@ EOF
 }
 
 # Turns off statsPlugin for these IPIMB boxes to prevent bogging down server and help Bld run at 120Hz
-helpBld(){
+helpBld()
+{
     if [[ $hutch == 'xcs' && ($BOXNAME == 'ipm3' || $BOXNAME == 'dio3') ]]; then
         # Attempt to caput values
         caput HFX:DG3:CVV:01:Stats2:EnableCallbacks 0
@@ -295,46 +297,46 @@ helpBld(){
         fi
     else
         echo 'Selected box has no known Bld issue to fix'
-	exit 1
+        exit 1
     fi
 }
 
 if [[ ($1 == "--help") || ($1 == "-h") ]]; then
-	usage
-	exit 0
+    usage
+    exit 0
 fi
 
 HUTCH=''
 BOXNAME=''
 HELPDAQBLD=0
-while getopts "b:H:dl" OPTION
-do
+while getopts "b:H:dl" OPTION; do
     case $OPTION in
-	H)
-	    HUTCH=${OPTARG^^}
-	    ;;
-	b)
-	    BOXNAME=$OPTARG
-	    ;;
-	d)
-	    HELPDAQBLD=1
-	    ;;
-	l)
-	    get_hutch
-	    ipmList
-	    exit 0
-	    ;;
-	?)
-	    usage
-	    exit 1
-	    ;;
-	esac
+        H)
+            HUTCH=${OPTARG^^}
+            ;;
+        b)
+            BOXNAME=$OPTARG
+            ;;
+        d)
+            HELPDAQBLD=1
+            ;;
+        l)
+            get_hutch
+            ipmList
+            exit 0
+            ;;
+        ?)
+            usage
+            exit 1
+            ;;
+    esac
 done
 
 get_hutch
 if [ ${#BOXNAME} == 0 ]; then
     ipmList
-    printf 'Enter box name from above list:\n'; read -r BOXNAME
+    printf 'Enter box name from above list:\n'
+    read -r BOXNAME
 fi
 
 ipmSetEnvPars "$BOXNAME"
diff --git a/scripts/motorInfo b/scripts/motorInfo
--- a/scripts/motorInfo
+++ b/scripts/motorInfo
@@ -1,7 +1,7 @@
 #!/bin/bash
 usage()
 {
-cat << EOF
+    cat << EOF
 $0 <motor_pv> <motor_pv_2|autosave|archive|pmgr_diff|pmgr_save> [opt]
 
 If given two motors, compare their settings
@@ -17,27 +17,26 @@ EOF
 }
 
 if [[ ($1 == "--help") || ($1 == "-h") ]]; then
-	usage
-	exit 0
+    usage
+    exit 0
 fi
 
-while getopts "f:s:e:" OPTION
-do
+while getopts "f:s:e:" OPTION; do
     case $OPTION in
-    f)
-	PVFIELDS=${OPTARG//,/}
-	;;
-    s)
-        export STARTTIME=$OPTARG
-	;;
-    e)
-        export ENDTIME=$OPTARG
-	;;
-    *)
-	echo "Invalid option \"$OPTION\" provided"
-	usage
-	exit 1
-	;;
+        f)
+            PVFIELDS=${OPTARG//,/}
+            ;;
+        s)
+            export STARTTIME=$OPTARG
+            ;;
+        e)
+            export ENDTIME=$OPTARG
+            ;;
+        *)
+            echo "Invalid option \"$OPTION\" provided"
+            usage
+            exit 1
+            ;;
     esac
 done
 
@@ -49,7 +48,7 @@ if [ $# -lt 2 ]; then
 fi
 
 MOTOR_PV=$(echo "$1" | cut -d . -f 1)
-if [[ $1 ==  "$MOTOR_PV" ]]; then
+if [[ $1 == "$MOTOR_PV" ]]; then
     FIELD=''
 else
     echo "1: $1"
@@ -60,11 +59,11 @@ fi
 
 source /reg/g/pcds/setup/pcds_shortcuts.sh
 
-if [[ $PVFIELDS == '' ]] && [[ "$2" != *pmgr* ]]; then
+if [[ $PVFIELDS == '' ]] && [[ $2 != *pmgr* ]]; then
     IOC_DIR='/reg/g/pcds/epics/'$(find_pv "$MOTOR_PV" | grep DIR | grep ims | awk '{print $2}')'/build/autosave'
     PVLIST=$("grep $MOTOR_PV $IOC_DIR/*req")
     for pv in $PVLIST; do
-	PVFIELDS=$(echo "$pv" | awk -F "$MOTOR_PV" '{ print $2 }')' '$PVFIELDS
+        PVFIELDS=$(echo "$pv" | awk -F "$MOTOR_PV" '{ print $2 }')' '$PVFIELDS
     done
 fi
 
@@ -73,75 +72,76 @@ if [[ $2 == 'autosave' ]]; then
 
     files=$(ls -t "$IOC_DIR"/*sav_1*)
     for field in $PVFIELDS; do
-	if [[ "$field" == *RBV* ]] || [[ "$field" == *VAL* ]] || [[ "$field" == *DESC* ]]; then
-	    continue
-	fi
-	echo "Looking at the autosave history for: $MOTOR_PV$field"
-	same_value_dat='now'
-	currVal=$(caget -t "$MOTOR_PV$field")
-	currValN=$(caget -tn "$MOTOR_PV$field")
-	for file in $files; do
-	    autoVal=$(grep "$MOTOR_PV$field " "$file" | awk '{print $2}')
-	    if [[ $autoVal != "$currValN" ]] && [[ ${#autoVal} -gt 0 ]]; then
-		#if $autoVal #check that this is not empty.
-		file_date=$(echo "$file" | awk -F sav_ '{ print $2 }')
-		if [[ $currVal != "$currValN" ]]; then
-		    echo "$MOTOR_PV$field current: $currValN '('$currVal')' -- $autoVal at $file_date , was same last: $same_value_dat"
-		else
-		    echo "$MOTOR_PV$field current: $currValN -- $autoVal at $file_date , was same last: $same_value_dat"
-		fi
-	    else
-		same_value_dat=$(echo "$file" | awk -F sav_ '{ print $2 }')
-	    fi
-	done
-	echo
+        if [[ $field == *RBV* ]] || [[ $field == *VAL* ]] || [[ $field == *DESC* ]]; then
+            continue
+        fi
+        echo "Looking at the autosave history for: $MOTOR_PV$field"
+        same_value_dat='now'
+        currVal=$(caget -t "$MOTOR_PV$field")
+        currValN=$(caget -tn "$MOTOR_PV$field")
+        for file in $files; do
+            autoVal=$(grep "$MOTOR_PV$field " "$file" | awk '{print $2}')
+            if [[ $autoVal != "$currValN" ]] && [[ ${#autoVal} -gt 0 ]]; then
+                #if $autoVal #check that this is not empty.
+                file_date=$(echo "$file" | awk -F sav_ '{ print $2 }')
+                if [[ $currVal != "$currValN" ]]; then
+                    echo "$MOTOR_PV$field current: $currValN '('$currVal')' -- $autoVal at $file_date , was same last: $same_value_dat"
+                else
+                    echo "$MOTOR_PV$field current: $currValN -- $autoVal at $file_date , was same last: $same_value_dat"
+                fi
+            else
+                same_value_dat=$(echo "$file" | awk -F sav_ '{ print $2 }')
+            fi
+        done
+        echo
     done
 elif [[ $2 == 'archive' ]]; then
     echo 'Command-line archiver is not implemented yet'
-elif [[ "$2" == *pmgr* ]]; then
+elif [[ $2 == *pmgr* ]]; then
     HUTCH=$(echo "$MOTOR_PV" | cut -d : -f 1)
     hutch=${HUTCH,,}
     ACTION=$(echo "$2" | cut -d _ -f 2)
     if [[ $ACTION == 'diff' ]]; then
-	/reg/g/pcds/config/"$hutch"/pmgr/pmgrUtils.sh "$ACTION" "$MOTOR_PV"
+        /reg/g/pcds/config/"$hutch"/pmgr/pmgrUtils.sh "$ACTION" "$MOTOR_PV"
     elif [[ $ACTION == 'save' ]]; then
-	echo "Differences of $MOTOR_PV to saved config:"
-	/reg/g/pcds/config/"$hutch"/pmgr/pmgrUtils.sh diff "$MOTOR_PV"
-	echo 'Save current config (yes/no)? '; read -r ANSWER
-	if [[ $ANSWER == 'yes' ]]; then
-	    echo 'Save now...'
-	    /reg/g/pcds/config/"$hutch"/pmgr/pmgrUtils.sh save "$MOTOR_PV"
-	    echo 'Saved.'
-	fi
+        echo "Differences of $MOTOR_PV to saved config:"
+        /reg/g/pcds/config/"$hutch"/pmgr/pmgrUtils.sh diff "$MOTOR_PV"
+        echo 'Save current config (yes/no)? '
+        read -r ANSWER
+        if [[ $ANSWER == 'yes' ]]; then
+            echo 'Save now...'
+            /reg/g/pcds/config/"$hutch"/pmgr/pmgrUtils.sh save "$MOTOR_PV"
+            echo 'Saved.'
+        fi
     else
-	echo "$ACTION is not yet implemented for the pmgr function of motorInfo"
+        echo "$ACTION is not yet implemented for the pmgr function of motorInfo"
     fi
 else
     MOTOR2_PV=$(echo "$2" | cut -d . -f 1)
     ADD_MOTOR_PV=$MOTOR2_PV
     echo "MOTORS DIFF $# $ADD_MOTOR_PV"
     while [[ $# -gt 2 ]]; do
-	shift
-	ADD_MOTOR_PV="$ADD_MOTOR_PV $(echo "$2" | cut -d . -f 1)"
+        shift
+        ADD_MOTOR_PV="$ADD_MOTOR_PV $(echo "$2" | cut -d . -f 1)"
     done
 
-    echo Field :  "$MOTOR_PV" -- "$ADD_MOTOR_PV"
+    echo Field : "$MOTOR_PV" -- "$ADD_MOTOR_PV"
     for field in $PVFIELDS; do
-	if [[ "$field" == *RBV* ]] || [[ "$field" == *VAL* ]]; then
-	    continue
-	fi
-	value_mot1=$(caget -t "$MOTOR_PV$field")
-	values=''
-	HAS_DIFF=0
-	for PV in $ADD_MOTOR_PV; do
-	    newval=$(caget -t "$PV$field")
-	    values=$values' - '$newval
-	    if [[ $value_mot1 != "$newval" ]]; then
-		HAS_DIFF=1
-	    fi
-	done
-	if [[ $HAS_DIFF -gt 0 ]]; then
-	    echo "$field" :  "$value_mot1" -- "$values"
-	fi
+        if [[ $field == *RBV* ]] || [[ $field == *VAL* ]]; then
+            continue
+        fi
+        value_mot1=$(caget -t "$MOTOR_PV$field")
+        values=''
+        HAS_DIFF=0
+        for PV in $ADD_MOTOR_PV; do
+            newval=$(caget -t "$PV$field")
+            values=$values' - '$newval
+            if [[ $value_mot1 != "$newval" ]]; then
+                HAS_DIFF=1
+            fi
+        done
+        if [[ $HAS_DIFF -gt 0 ]]; then
+            echo "$field" : "$value_mot1" -- "$values"
+        fi
     done
 fi
diff --git a/scripts/pkg_release b/scripts/pkg_release
--- a/scripts/pkg_release
+++ b/scripts/pkg_release
@@ -1,7 +1,7 @@
 #!/bin/bash
 usage()
 {
-cat << EOF
+    cat << EOF
 usage: $0 [organization] <repo> <tag>
 
 Checks out a Github repository into the current directory, from the pcdshub organization unless told otherwise.
@@ -11,62 +11,62 @@ EOF
 }
 
 if [[ ($1 == "--help") || ($1 == "-h") ]]; then
-	usage
-	exit 0
+    usage
+    exit 0
 fi
 
 if [ $# -eq 2 ]; then # pcdshub is default organization
-  ORG="pcdshub"
-  PACKAGE="${1}"
-  TAG="${2}"
+    ORG="pcdshub"
+    PACKAGE="${1}"
+    TAG="${2}"
 elif [ $# -eq 3 ]; then # allow other orgs if provided
-  ORG="${1}"
-  PACKAGE="${2}"
-  TAG="${3}"
+    ORG="${1}"
+    PACKAGE="${2}"
+    TAG="${3}"
 else # display usage if used with improper number of arguments
-  usage
-  exit
+    usage
+    exit
 fi
 
 URL="https://github.com/${ORG}/${PACKAGE}"
 SSH_URL="git@github.com:${ORG}/${PACKAGE}"
 TEMP="pkg_release_tempdir"
 if [ -d "${TEMP}" ]; then
-  echo "Removing leftover ${TEMP} directory..."
-  rm -rf "${TEMP}"
+    echo "Removing leftover ${TEMP} directory..."
+    rm -rf "${TEMP}"
 fi
 echo "Testing connection to github.com" # Check connection before running clone
 if ! ping -c 1 github.com &> /dev/null; then
-  echo "github.com not responding to ping. Exiting."
-  exit
+    echo "github.com not responding to ping. Exiting."
+    exit
 fi
 echo "Connection successful."
 TEST_OUTPUT=$(ssh -Tx git@github.com 2>&1) # Test ssh key with github and use ssh if appropriate, https otherwise
 if echo "$TEST_OUTPUT" | grep "successfully authenticated" > /dev/null; then
-  echo "Attemping clone using SSH..."
-  echo "URL = $SSH_URL"
-  set -e  # Catch error in git clone
-  git clone "${SSH_URL}" "${TEMP}"
+    echo "Attemping clone using SSH..."
+    echo "URL = $SSH_URL"
+    set -e # Catch error in git clone
+    git clone "${SSH_URL}" "${TEMP}"
 elif echo "$TEST_OUTPUT" | grep "Permission denied\|no kex alg" > /dev/null; then
-  echo "Attemping clone using HTTPS..."
-  echo "URL = $URL"
-  set -e  # Catch error in git clone
-  git clone "${URL}" "${TEMP}"
+    echo "Attemping clone using HTTPS..."
+    echo "URL = $URL"
+    set -e # Catch error in git clone
+    git clone "${URL}" "${TEMP}"
 else
-  echo "Error: $TEST_OUTPUT"
-  exit
+    echo "Error: $TEST_OUTPUT"
+    exit
 fi
 set +e
 echo "Checking out tag..."
 pushd "${TEMP}"
-git tag -l | grep "${TAG}" >/dev/null
+git tag -l | grep "${TAG}" > /dev/null
 if [ "${?}" == "1" ]; then
-  echo "Error: could not find tag \"${TAG}.\" Aborting."
-  echo "Available tags:"
-  git tag -l
-  exit
+    echo "Error: could not find tag \"${TAG}.\" Aborting."
+    echo "Available tags:"
+    git tag -l
+    exit
 fi
-set -e  # Catch error in git checkout
+set -e # Catch error in git checkout
 git checkout "${TAG}"
 popd
 echo "Renaming \"${TEMP}\" directory to ${TAG}"
diff --git a/scripts/pydev_register b/scripts/pydev_register
--- a/scripts/pydev_register
+++ b/scripts/pydev_register
@@ -1,7 +1,7 @@
 #!/bin/bash
 usage()
 {
-cat << EOF
+    cat << EOF
 usage: $0 <path> module|bin
 
 Use this script to register development packages so that they will be
@@ -10,29 +10,29 @@ EOF
 }
 
 if [[ ($1 == "--help") || ($1 == "-h") ]]; then
-	usage
-	exit 0
+    usage
+    exit 0
 fi
 
 if [ -z "${1}" ]; then
-  usage
-  exit
+    usage
+    exit
 elif [ ! -e "${1}" ]; then
-  echo "Path Does Not Exist" >&2
-  usage
-  exit 1
+    echo "Path Does Not Exist" >&2
+    usage
+    exit 1
 fi
 
 PYDEV_DIR=~/pydev
 full_path=$(readlink -f "$1")
 if [ "${2}" == "module" ]; then
-  link="${PYDEV_DIR}"
+    link="${PYDEV_DIR}"
 elif [ "${2}" == "bin" ]; then
-  link="${PYDEV_DIR}/bin"
+    link="${PYDEV_DIR}/bin"
 else
-  echo "Invalid input."
-  usage
-  return
+    echo "Invalid input."
+    usage
+    return
 fi
 mkdir -p "${PYDEV_DIR}/bin"
 ln -sf "${full_path}" "${link}"
diff --git a/scripts/set_gem_timing b/scripts/set_gem_timing
--- a/scripts/set_gem_timing
+++ b/scripts/set_gem_timing
@@ -8,21 +8,21 @@ IOC_PATH_SC="ioc/fee/GasDetDAQ/R4.0.22-NOTS"
 IOC_PATH=0
 
 # User input validation
-if [[ -n $1 ]]; then # if the user passed at least one arg
-  if [[ $1 != "$NC_STRING" ]] && [[ $1 != "$SC_STRING" ]]; then #validate argument is either SC or NC
-    echo "Error. Argument must be either: [NC or SC]"
-    exit 1
-  else
-    echo "User passed argument of: $1"
-  fi
+if [[ -n $1 ]]; then                                              # if the user passed at least one arg
+    if [[ $1 != "$NC_STRING" ]] && [[ $1 != "$SC_STRING" ]]; then #validate argument is either SC or NC
+        echo "Error. Argument must be either: [NC or SC]"
+        exit 1
+    else
+        echo "User passed argument of: $1"
+    fi
 else
-  echo "Error. Must pass at least one argument"
-  exit 1
+    echo "Error. Must pass at least one argument"
+    exit 1
 fi
 
 if [[ -n $2 ]]; then
-  echo "Error. Must pass strictly one argument, at least one additional arg: $2, please run again with exclusively [NC or SC] as argument"
-  exit 1
+    echo "Error. Must pass strictly one argument, at least one additional arg: $2, please run again with exclusively [NC or SC] as argument"
+    exit 1
 fi
 
 #get caget and caput
@@ -35,27 +35,27 @@ OP_MODE=$(caget KFE:CAM:TPR:02:MODE | awk '{print $2}')
 SET_MODE_CMD="caput KFE:CAM:TPR:02:MODE $1"
 
 echo "Current OP_MODE is: $OP_MODE"
-if [[ $OP_MODE = "$1" ]]; then
-  echo "Warning. Already in requested mode: $OP_MODE" #Note: (josh) we are opting to consider this not error worthy
+if [[ $OP_MODE == "$1" ]]; then
+    echo "Warning. Already in requested mode: $OP_MODE" #Note: (josh) we are opting to consider this not error worthy
 else
-  echo "Actuating requested timing change, caputing $1 to KFE:CAM:TPR:02:MODE"
-  $SET_MODE_CMD
+    echo "Actuating requested timing change, caputing $1 to KFE:CAM:TPR:02:MODE"
+    $SET_MODE_CMD
 fi
 
 # only now discern which mode we want to put it in, TODO(josh): theres some more bashy way of string unwrapping todo this....
-if [[ $1 = "$NC_STRING" ]]; then
-  IOC_PATH=$IOC_PATH_NC
+if [[ $1 == "$NC_STRING" ]]; then
+    IOC_PATH=$IOC_PATH_NC
 else
-  IOC_PATH=$IOC_PATH_SC
+    IOC_PATH=$IOC_PATH_SC
 fi
 
 SET_IOC_PATH_CMD="${IMGR_CMD_PATH} ioc-lfe-gasdet-daq --upgrade $IOC_PATH"
 CURR_IOC_PATH=$(${IMGR_CMD_PATH} ioc-lfe-gasdet-daq --info | awk 'FNR == 4 {print $3}') #Warning: make sure your release of imgr supports --info
-if [[ $CURR_IOC_PATH = "$IOC_PATH" ]]; then
-  echo "Current IOC path is: $CURR_IOC_PATH which is equiavlent to requested IOC path for the requested switch to $1, not invoking imgr"
+if [[ $CURR_IOC_PATH == "$IOC_PATH" ]]; then
+    echo "Current IOC path is: $CURR_IOC_PATH which is equiavlent to requested IOC path for the requested switch to $1, not invoking imgr"
 else
-  echo "Actuating ioc-lfe-gasdet-daq IOC software change from $CURR_IOC_PATH to: $IOC_PATH"
-  $SET_IOC_PATH_CMD
+    echo "Actuating ioc-lfe-gasdet-daq IOC software change from $CURR_IOC_PATH to: $IOC_PATH"
+    $SET_IOC_PATH_CMD
 fi
 
 exit 0
