[ENH] makepeds_psana: check for error after each sbatch submission

diff --git a/scripts/makepeds_psana b/scripts/makepeds_psana
--- a/scripts/makepeds_psana
+++ b/scripts/makepeds_psana
@@ -56,6 +56,14 @@ OPTIONS:
 EOF
 }
 
+check_for_submit_error()
+{
+    if [[ $? != 0 ]]; then
+        echo "Submission failed. Does the user have permission to submit with experiment account?"
+        exit 1
+    fi
+}
+
 check_running_jobs()
 {
     declare -A SLURM_STAT_MSG=( ["R"]="is RUNNING."
@@ -103,6 +111,7 @@ xtcav_dark()
        xtcavCmd="sbatch --exclusive  --account lcls:$EXP -p $QUEUE -o $WORKDIR/xtcav_${EXP}_Run${RUN}_%J.out $tmpScript"
        echo "run in queue: $xtcavCmd"
        SUBMISSION=$($xtcavCmd)
+       check_for_submit_error
        echo "$SUBMISSION"
        THISJOBID=$(echo "$SUBMISSION" | awk '{print $4}')
        JOBIDS+=( "$THISJOBID" )
@@ -137,6 +146,7 @@ xtcav_lasOff()
        xtcavCmd="sbatch --exclusive  --account lcls:$EXP -p $QUEUE -o $WORKDIR/xtcav_${EXP}_Run${RUN}_%J.out $tmpScript"
        echo "run in queue: $xtcavCmd"
        SUBMISSION=$($xtcavCmd)
+       check_for_submit_error
        echo "$SUBMISSION"
        THISJOBID=$(echo "$SUBMISSION" | awk '{print $4}')
        JOBIDS+=( "$THISJOBID" )
@@ -610,6 +620,7 @@ if [[ $LCLS2 -gt 0 ]]; then
                         fi
                         echo "run in queue: $ep10kaCmd"
                         SUBMISSION=$($ep10kaCmd)
+                        check_for_submit_error
                         echo "$SUBMISSION"
                         THISJOBID=$(echo "$SUBMISSION" | awk '{print $4}')
                         JOBIDS+=( "$THISJOBID" )
@@ -760,6 +771,7 @@ if [[ ( $HAVE_JUNGFRAU -ge 1 ) && ( $WANT_ZYLA -eq 0 ) && ( $WANT_OPAL -eq 0 ) &
                 fi
                 echo "run in queue: $jfCmd"        
                 SUBMISSION=$($jfCmd)
+                check_for_submit_error
                 echo "$SUBMISSION"
                 THISJOBID=$(echo "$SUBMISSION" | awk '{print $4}')
                 JOBIDS+=( "$THISJOBID" )
@@ -864,6 +876,7 @@ if [[ ( $HAVE_EPIX10K -ge 1 ) && ( $WANT_ZYLA -eq 0 ) && ( $WANT_OPAL -eq 0 ) &&
                 fi
                 echo "run in queue: $ep10kaCmd"
                 SUBMISSION=$($ep10kaCmd)
+                check_for_submit_error
                 echo "$SUBMISSION"
                 THISJOBID=$(echo "$SUBMISSION" | awk '{print $4}')
                 JOBIDS+=( "$THISJOBID" )
