ENH: Added check for Beckhoff axis

diff --git a/scripts/motor-expert-screen b/scripts/motor-expert-screen
--- a/scripts/motor-expert-screen
+++ b/scripts/motor-expert-screen
@@ -1,3 +1,5 @@
+isbeckhoff=false
+
 #!/bin/bash
 
 OLD_VERSION='R2.5.0'
@@ -31,26 +33,27 @@ export EDMDATAFILES=.:${PCDS_EDMS}/xps8:/reg/g/pcds/package/epics/3.14/ioc/commo
 source /reg/g/pcds/setup/pathmunge.sh
 ldpathmunge /usr/local/lib
 
-# Check to see if this is a Beckhoff axis
-#   caget will return exit code 0 if :PLC:nErrorId_RBV exists, 
-#   we set isbeckhoff based on this.
+# bool used to to deterime if a motor with .rtyp == 'motor' is a Beckhoff axis.
 isbeckhoff=false
-caget "${PREFIX}:PLC:nErrorId_RBV" > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    isbeckhoff=true
-fi
 
 # Choose title so we can move the right window.
 # If this script hangs later, titles probably changed.
 rtyp=`caget -t $PREFIX.RTYP` > /dev/null 2>&1
-if [ ${isbeckhoff} == true ]; then
-    title="Typhos Suite - ${PREFIX}"
-elif [ "${rtyp}" == 'xps8p' ]; then
+if [ "${rtyp}" == 'xps8p' ]; then
     title='Newport XPS Positioner'
 elif [ "${rtyp}" == 'ims' ]; then
     title='IMS Motor Control -- Main'
 elif [ "${rtyp}" == 'motor' ]; then
-    title='Aerotech motor'
+    # Check to see if this is a Beckhoff axis
+    #   caget will return exit code 0 if :PLC:nErrorId_RBV exists,
+    #   we set isbeckhoff based on this.
+    caget "${PREFIX}:PLC:nErrorId_RBV" > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        title="Typhos Suite - ${PREFIX}"
+        isbeckhoff=true;
+    else
+        title='Aerotech motor'
+    fi
 else
     caget "$PREFIX.PN" > /dev/null 2>&1
     if [ $? -eq 0 ]; then
