Updated pkg_release to look at slaclab and added SSH cloning functionality with connection checks

diff --git a/scripts/pkg_release b/scripts/pkg_release
--- a/scripts/pkg_release
+++ b/scripts/pkg_release
@@ -9,20 +9,35 @@ if [ -z "${2}" ]; then
 fi
 PACKAGE="${1}"
 TAG="${2}"
-URL="https://github.com/pcdshub/${PACKAGE}"
+URL="https://github.com/slaclab/${PACKAGE}"
+SSH_URL="git@github.com:slaclab/${PACKAGE}"
 TEMP="pkg_release_tempdir"
 if [ -d "${TEMP}" ]; then
   echo "Removing leftover ${TEMP} directory..."
   rm -rf "${TEMP}"
 fi
-echo "Checking that repo exists..."
-curl -s --head "${URL}" | head -n 1 | grep "HTTP/1.[01] [23].." >/dev/null
-if [ "${?}" == "1" ]; then
-  echo "Error: could not reach repo at URL ${URL}. Aborting."
+echo "Testing connection to github.com"
+if ! ping -c 1 github.com &> /dev/null; then
+  echo "github.com not responding to ping. Exiting."
   exit
 fi
-set -e  # Catch error in git clone
-git clone "${URL}" "${TEMP}"
+echo "Connection successful."
+TEST_OUTPUT=$(ssh -Tx git@github.com 2>&1)
+if echo $TEST_OUTPUT | grep "successfully authenticated" > /dev/null; then
+  echo "Attemping clone using SSH..."
+  echo "URL = $SSH_URL"
+  set -e  # Catch error in git clone
+  git clone "${SSH_URL}" "${TEMP}"
+elif echo $TEST_OUTPUT | grep "Permission denied\|no kex alg" > /dev/null; then
+  echo "Attemping clone using HTTPS..."
+  echo "URL = $URL"
+  set -e  # Catch error in git clone
+  git clone "${URL}" "${TEMP}"
+else
+  echo "Error: "
+  ssh -Tx git@github.com
+fi
+unset TEST_OUTPUT
 set +e
 echo "Checking out tag..."
 pushd "${TEMP}"
