ENH: Rewrite/fix dss node code in serverStat

diff --git a/scripts/serverStat b/scripts/serverStat
--- a/scripts/serverStat
+++ b/scripts/serverStat
@@ -141,24 +141,27 @@ if [[ $ISSRV -lt 1 ]] && [[ $HUTCH != 'unknown_hutch' ]]; then
         CNF="/reg/g/pcds/dist/pds/${HUTCH}/scripts/${HUTCH}.cnf"
     fi
 
-    if [[  $DEV == *'event'* ]]; then
-        DSSNODES=$(grep dss_nodes "$CNF" | grep -v '#' | head -n1)
-        i=$((${#DEV}-1));NEV=$(echo "${DEV:$i:1}");AWKNUM=$(($NEV+4))
-        NAME=$(echo "$DSSNODES" | awk -v temp=$AWKNUM '{print $temp}'  |  sed s/,// | sed s/_/-/g | sed s/\'//g | sed s/-fez//g)
+    if [[  $DEV =~ 'event' ]]; then
+        DSSNODES=$(grep dss_nodes "$CNF" | grep -v '^#' | head -n1)
+        NEVENT=$(echo "${DEV:5}")  # grab the index (e.g. 2 if $DEV is event2)
+        AWKNUM=$(($NEVENT+3))  # adjust the number to grab the hostname correctly
+        NAME=$(echo "$DSSNODES" | awk -v temp=$AWKNUM '{print $temp}' | tr -dc '[:alnum:]-')
     else
         NDEV=$(grep "$DEV" "$CNF" | grep -v '#' | grep host | wc -l)
         if [ "$NDEV" -eq 1 ]; then
             NAME=$(grep "$DEV" "$CNF" | grep -v '#' | grep host | awk '{print $1}' | sed s/{host://g | sed s/,// | sed s/_/-/g | sed s/\'//g | sed s/-fez//g)
         elif  [ "$NDEV" -eq 0 ]; then
-            echo 'no device of this name found, exit'
+            echo 'No device of this name found, exiting...' >&2
             exit 1
         else
             NAME=$(grep "$DEV'" "$CNF" | grep -v '#' | grep host | awk '{print $1}' | sed s/{host://g | sed s/,// | sed s/_/-/g)
         fi
     fi
-    ISSRV=$(netconfig search "$NAME" | grep 'Found' | awk '{print $2}')
+    if [[ $NAME ]]; then
+        ISSRV=$(netconfig search "$NAME" | grep 'Found' | awk '{print $2}')
+    fi
     if [[ $ISSRV -lt 1 ]]; then
-        echo 'does not have ipmi, is not DAQ device.'
+        echo "Host ($NAME) not found in netconfig, exiting..." >&2
         exit 1
     fi
 
