ENH: Make the dss search more robust

diff --git a/scripts/serverStat b/scripts/serverStat
--- a/scripts/serverStat
+++ b/scripts/serverStat
@@ -146,10 +146,14 @@ if [[ $ISSRV -lt 1 ]] && [[ $HUTCH != 'unknown_hutch' ]]; then
     fi
 
     if [[  $DEV =~ 'event' ]]; then
-        DSSNODES=$(grep dss_nodes "$CNF" | grep -v '^#' | head -n1)
+        DSSNODES=$(grep dss_nodes "$CNF" | grep -v '^#' | head -n1 | grep -oE "daq-$HUTCH-dss[[:digit:]]+")
         NEVENT=$(echo "${DEV:5}")  # grab the index (e.g. 2 if $DEV is event2)
-        AWKNUM=$(($NEVENT+3))  # adjust the number to grab the hostname correctly
-        NAME=$(echo "$DSSNODES" | awk -v temp=$AWKNUM '{print $temp}' | tr -dc '[:alnum:]-')
+        SEDNUM=$(($NEVENT+1))  # adjust the number to correctly index the list of dssnodes with sed
+        NAME=$(echo "$DSSNODES" | sed -n ${SEDNUM}p)
+        if [[ -z $NAME ]]; then
+            echo "dss node not found for $DEV, exiting..." >&2
+            exit 1
+        fi
     else
         NDEV=$(grep "$DEV" "$CNF" | grep -v '#' | grep host | wc -l)
         if [ "$NDEV" -eq 1 ]; then
